mechanical_kpi_reference = {
# direct_data_reference = {
    "Pipe LF": 47,
    "Pipe Fittings": 48,
    "Pipe Valves": 49,
    "Pipe Supports": 50,
    "Instruments": 51,
    "Pipe Welds": 52,
    "Pipe Weld Dia\"": 53,
    "Average Pipe Size\"": 54,
    "Pipe Insulation LF": 55,
    "Excavation Qty": 56,  
    "Equipment Qty": 57,
    "Structural Steel Fab Weight": 58,
    "Structural Steel Erection Weight": 59,
    "Welds to Inspect": 60,
    "Direct Piping Manhours": 61,
    "Equipment Manhours": 62,
    "Structural Steel Fab Manhours": 63,
    "Structural Steel Erection Manhours": 64,
    "Pipe Testing Manhours": 65,
    "Pipe Labeling Manhours": 66,
    "Valve Tag Manhours": 67,
    "Total Direct Craft Manhours": 68,
    "InServ Project Staff Manhours": 69,
    "VDC Manhours": 70,
    "Indirect Craft Manhours": 71,
    "Job Mob, Demob & Setup": 72,
    "Safety Orientation & Testing": 73,
    "Total Direct & Indirect Craft Manhours": 74,
# material_data_reference = {
    "Total Pipe Material Cost": 76,
    'Total Equipment Material Cost': 77,
    'Total Structural Steel Material Cost': 78,
    'Total Pipe Label Material Cost': 79,
    "Total Valve Tag Material Cost": 80,
    "Total Major Equipment Cost": 81,
# indirect_data_reference= {
    "InServ Owned Equipment Cost": 83,
    "3rd Party Rental Cost": 84,
    'Small Tools & Machines': 85,
    'Consumable Supplies': 86,
    'Welding Rod Material': 87,
    'Oxygen-Acetylene Gases': 88,
    'Alloy Weld Rod/Inert Gas': 89,
    'Total Material Cost': 90,
    'Safety Orientation Training Cost': 91,
    'Per Diem': 92,
    'Direct Craft Labor $ (incl Burden)': 93,
    'Indirect Craft Labor $ (incl Burden)': 94,
    'Indirect Staff Labor $ (incl Burden)': 95,
    'Indirect VDC Labor $ (incl Burden)': 96,
    'Contract Labor $': 97,
    'Total Labor $': 98,
    'Total Quote $': 99,
# labor_checks_reference = {
    'Unapplied Super/Total Direct Hours': 101,
    'PM hours/Total Direct hours': 102,
    'Direct Piping Manhours/LF': 103,
    'Direct Piping Manhours/Fitting': 104,
    'Direct Piping Manhours/Valve': 105,
    'Direct Piping Manhours/Instrument': 106,
    'Direct Piping Manhours/Weld': 107,
    'Direct Steel Fab Manhours/LB': 108,
    'Direct Steel Erection Manhours/Ton': 109,
    'Total Indirect Craft Labor $/Total Direct Craft Labor $': 110,
    'Total Indirect Craft Mhrs/Total Direct Craft Mhrs': 111,
# subcontractor_checks_reference = {
    'Insulation Cost$/LF': 113,
    'Painting Cost$/SF': 114,
    'Excavation Total Cost$/CY': 115,
    'Excavation Equipment Cost$/CY': 116,
    'Excavation Labor Hours/CY': 117,
    'Excavation Average Depth': 118,
# material_checks_reference = {
    'Small Tools & Consumables/Direct Field Labor $': 120,
    'Small Tools & Consumables$/LF of Pipe': 121,
    'Small Tools & Consumables$/Fitting': 122,
    'Small Tools & Consumables$/FTG, Valve, Instrument': 123,
    'Weld Gas$/Direct Craft Labor Hours': 124,
    'Weld Gas$/Orbital Welding Machine Rental Weeks': 125,
# equipment_checks_reference = {
    'Total Equipment w/Crane $/Total Craft Labor Hours': 127,
    'Total Equipment without Crane $/Total Craft Labor Hours': 128,
    'Crane Cost$/Total Craft Labor Hours': 129,
    'Service Truck $/Total Craft Labor Hours': 130,
# safety_checks_reference = {
    "Safety Orientation & Testing Hours/Total Craft Hours": 132,
# financial_checks_reference = {
    'Labor': 134,
    'Material': 135,
    'Major Equipment': 136,
    'Const Equipment': 137,
    'Subs': 138,
    'Other (Gen Cond, Travel, Per Diem)': 139,
    'OH&P': 140,
    'Labor Risk Coverage DL$/OH&P': 141,
# perdiem_checks_reference = {
    'Total Per Diem $/Total Craft Hour': 143,
    'Total Per Diem $/Total Craft $': 144,
# VDC_checks_reference = {
    'VDC$/Total Quote$': 146,
    'VDC$/Total Labor Cost$': 147,
    'VDC$/LF of Pipe': 148,
    'VDC$/LB of Steel': 149,
    'VDC$/Pound of Duct': 150,
    'VDC$/CFM': 151,
# conceptual_checks_reference = {
    'Cost of Major Equipment/Total Project Quote': 153,
    'Total Project Cost$/SF': 154,
    'Total Project Cost$/LF': 155,
    'Total Project Cost$/TON': 156,
    'Total Project Cost$/CFM': 157,
    'Total Quote $/Total General Contractor Cost': 158,
}

bid_info_reference = {
    'Bid Type': 5,
    'Division': 6,
    'Market Segment': 7,
    '# of Floors': 10,
    'Project Size': 11,
    'Construction Type': 12,
    'Facility Type': 13,
    'Floor to Floor Height': 14,
    'Building Sq. Ft.': 15,
    'Bond Req\'d (Yes or No)': 17,
    'Contract Type': 18,
    'Delivery Method': 19,
    'Payment Terms - Net': 20,
    'Client': 21,
    'RFQ Reference Data': 23,
    'Start Date': 25,
    'Finish Date': 26,
    'Days Per Week': 27,
    'Hours Per Day': 28,
    'Days': 29,
    'Weeks': 30,
    'Months': 31,
    'Estimator': 33,
    'Estimator-HVAC': 34,
    'Estimator-Plumbing': 35,
    'Address': 37,
    'Project Name': 39,
    'Quote ID Number': 40,
    'Proposal Due Date':45,
}